quantities/tests/test_uncertainty.py, quantities/uncertainquantity.py
handle uncertainty in x-x case (different than x-y).
=> subtraction of same element handled correctly

quantities/units/pressure.py
Hi,
I would like to propose correcting an object name in line 66 as followings, considering the meanings of kilobar and megabar.
From: Mbar = kilobar = UnitQuantity(
To: Mbar = megabar = UnitQuantity(
Best regards,
=> Proposed correction from kilobar to megabar

.travis.yml
Test python-quantities against newer numpy versions and against py3.5.
=> Travis numpy up

quantities/tests/test_uncertainty.py, quantities/uncertainquantity.py
This should fix #115
I should mention that I checked that the added test fail without the proposed patch to `UncertainQuantity`.
=> Fix negative UncertainQuantity

quantities/decorators.py, quantities/quantity.py, quantities/tests/test_methods.py
The main part of this PR is to add `real` and `imag` wrappers, that check and apply proper units. I've also included a fix to the `quantitizer` decorator, which was mistakenly adding a call to `simplified`.
=> Add imag/real wrappers.

quantities/dimensionality.py, quantities/markup.py, quantities/tests/test_dimensionality.py
In analogy with `.latex`
Let me know what you think.
=> Add property html to Dimensionality

.gitignore, CHANGES.txt, README.rst, conda.recipe/run_test.py, doc/devel/devnotes.rst, doc/user/installation.rst, quantities/tests/common.py, setup.py
in preparation for a possible 0.12.0 release
=> Updates to the documentation

quantities/units/time.py
corrected bug: kiloseconds was incorrectly refenced as ms instead of ks
=> URGENT: changed ms to ks

quantities/quantity.py, quantities/tests/test_umath.py
This PR should enable `numpy.linspace` to work (fixes gh-105)
=> Fix numpy.linspace

.travis.yml
Test python-quantities with more numpy versions.
=> Increase CI test space

quantities/quantity.py, quantities/tests/test_conversion.py
=> Implemented preferred rescaling

quantities/units/temperature.py
See table in
https://en.wikipedia.org/wiki/Orders_of_magnitude_(temperature)#SI_multiples
=> Add SI multiples for Kelvin

quantities/__init__.py, quantities/markup.py
=> Fix backslash escapes

README.rst
=> Replace Travis CI badge in README with Actions badge.

quantities/units/length.py
=> Add decimeter to list of supported units

quantities/dimensionality.py, quantities/tests/test_arithmetic.py
=> fix failure to handle units with floordiv

quantities/units/electromagnetism.py
Pull request to address issue  #209.
Four lines were added to define fF as a UnitQuantity.
=> Added femtofarad (fF) to the units.

quantities/quantity.py, quantities/tests/test_conversion.py, quantities/tests/test_methods.py
=> Fix gh-215, dtype conversion in rescale

.github/workflows/test.yml, quantities/__init__.py, quantities/dimensionality.py, quantities/quantity.py, quantities/tests/common.py, quantities/tests/test_arithmetic.py, quantities/tests/test_methods.py, quantities/tests/test_umath.py, quantities/uncertainquantity.py
this is built off of #232 
Since I don't know array wrapping perfectly I may need to tweak this again.
=> Add numpy 2.0 compatibility

.github/workflows/test.yml
following a policy of NEP 29 + 1 year.
=> Update CI matrix

quantities/dimensionality.py, quantities/tests/test_umath.py
Noticed that these were missing.
=> Add umath funcs: maximum & minimum

.github/workflows/test.yml, quantities/registry.py, quantities/tests/test_units.py
Based on https://stackoverflow.com/a/11952618 by https://stackoverflow.com/users/567292/ecatmur
Fixes #250
Also added test for the original issue: #221
=> An alternative approach to avoiding arbitrary evaluation of code when parsing strings as units

quantities/units/force.py, quantities/units/force.pyi
=> Add kilonewton
