quantities/quantity.py, quantities/tests/test_methods.py
Most importantly, this PR fixes #69: The `axis` parameters that did not get forwarded on `min`, `max` and `ptp`. It also properly implements the `out` parameter, guaranteeing that the returned Quantity is indeed the same as the passed one.
=> Fixes axis and out parameters on Quantity methods

.travis.yml, README.rst, README.txt
This is a minor PR for updating the README and travis test script.
Changes to travis script:
- Also test for Python 3.4
- Change tested version of `numpy` from v1.7.0 to:
- v1.7.1
- v1.9.1
To see what the proposed README.rst renders like, see:
https://github.com/bjodah/python-quantities/tree/update_readme_travis
=> Updated README and travis script

.travis.yml, quantities/dimensionality.py, quantities/quantity.py, quantities/tests/test_arithmetic.py, quantities/unitquantity.py
I don't see this on Python 2. Hopefully reproducible on Travis.
=> Fix python3.5 regression (raising to the zeroth power)

quantities/units/electromagnetism.py
The siemens unit was broken, e.g., "qt.pS == qt.siemens" would return "True"
=> fixed unit siemens, S, mS etc.

.travis.yml, quantities/tests/test_umath.py
(since Python 2.6 is not supported by NumPy 1.12+)
=> Add NumPy 1.12 and 1.13 to Travis CI test matrix, and remove Python 2.6

quantities/units/electromagnetism.py
These units are used e.g. in electron beam lithography.
=> Add microcoulomb and millicoulomb units

quantities/units/pressure.py
Fix support for the unit mbar that was introduced in #72. The problem
with mbar is that pq.Quanitty('mbar') raises a LookupError without this
fix.
=> Fix broken support for pq.Quantity('mbar')

quantities/quantity.py, quantities/tests/test_formatting.py
Closes #156
This fix is a slightly adapted version of
https://github.com/yt-project/unyt/commit/e57e1ecc1214deee36ba679f08ee46c6aa6aefbe
If we want to keep support for older versions of numpy we have to add a
numpy version check. For simplicity I dropped support for older versions
of numpy. I hope that this is fine.
Edit: Added the numpy version check.
=> Add a __format__ implementation for Quantity

quantities/dimensionality.py
This commit adds support for the ufunc `clip` added by Numpy 1.17 and thus removes the error: "ValueError: ufunc <ufunc 'clip'> not supported by quantities".
Fixes: python-quantities#158
=> Fix "<ufunc 'clip'> not supported error

quantities/dimensionality.py, quantities/tests/test_umath.py
Due to a change in numpy 1.16.0 ndarray subclasses (=pq.Quantity) were
treated differently by, e.g., np.angle if quantities were passed as arguments.
This change ensures that np.arctan2 returns a dimensionless quantity.
Closes #161
=> Fix np.arctan2 regression due to newer numpy version

quantities/units/dimensionless.py
The dimensionless qualifier 'lsb' (least significant bit) is commonly used  when describing the behavior of electronic instruments, especially in the context of A/D and D/A converters. It denotes a given change of the digital value in units of the smallest possible change – one LSB.
=> Add dimensionless unit 'lsb'

.github/workflows/test.yml, doc/user/installation.rst, quantities/markup.py, setup.py
i.e. continue to support Python/NumPy versions for one year longer than [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommends.
(see discussion in #195)
=> Extend the testing matrix to NEP29 + 1 year

doc/devel/documenting.rst, quantities/decorators.py, quantities/quantity.py, quantities/umath.py
There are small typos in:
- doc/devel/documenting.rst
- quantities/decorators.py
- quantities/quantity.py
- quantities/umath.py
Fixes:
- Should read `updating` rather than `updateing`.
- Should read `replace` rather than `repalce`.
- Should read `quantities` rather than `quanitities`.
- Should read `necessary` rather than `necesssary`.
- Should read `mimics` rather than `mimicks`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

quantities/units/pressure.py
In order to be consistent with the other pressure units that are derived
from the unit bar, we should use mbar as the symbol for millibar. The
symbol mb, which is a deprecated symbol, because the b in mb conflicts
with the metric unit barn, was removed. Since the other bar units also
define an alias with a written out SI prefix, this change also adds the
unit "millibars" as an alias for mbar.
https://en.wikipedia.org/wiki/Bar_(unit)#Origin Also mentions that b is
a deprecated symbol for bar.
=> Remove deprecated mb as symbol for millibar unit

quantities/dimensionality.py, quantities/quantity.py, quantities/tests/test_arithmetic.py, quantities/tests/test_umath.py, quantities/tests/test_uncertainty.py, quantities/uncertainquantity.py
There are also some lines in `def astype` which look suspicious, (dtype is not propagated), but I have yet to come up with a small test for those. But I think this changeset is sensible on its own.
=> Preserve dtype in rescale

quantities/quantity.py, quantities/tests/test_umath.py
Also `np.trapz` will be deprecated, and the recommendation is to switch to using a scipy function instead. I can delete trapz in this PR if you want or just leave it alone until it becomes a hard error.
=> Switch `np` aliases which will be removed in NumPy 2.0

quantities/umath.py
I just built on top of my other PR #227, so that should be merged first.
I just did a straight port of the numpy implementation, and since the docstring will likely be removed I copied over the docstring as well. This way the behavior stays exactly the same as it was before for users. But if you want a different strategy feel free to close @apdavison.
=> Port `np.trapz` into umath since it will be removed in a future version of numpy

.github/workflows/test.yml, pyproject.toml
Add Python 3.12, NumPy 1.25 and 1.26, remove Numpy 1.19
(reminder that we follow [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) plus one year)
=> Update CI test matrix

.github/workflows/test.yml, quantities/__init__.py, quantities/dimensionality.py, quantities/quantity.py, quantities/tests/common.py, quantities/tests/test_arithmetic.py, quantities/tests/test_methods.py, quantities/tests/test_umath.py, quantities/uncertainquantity.py
Seems like NumPy 2.0 broke some behavior which quantities relied on. This PR allows the test suite to pass for me locally. I have not addressed any deprecation warnings that are new in numpy 2.0. I'm thinking that we can fix those in a subsequent PR.
Let me know what you think.
=> Add support for NumPy 2.0

quantities/registry.py
Fixes #221.
@codingchipmunk feel free to look at this. It's a bit of a hammer, but this blocks arbitrary eval of any python built-ins.
@apdavison, I would say this type of security would be nice to have even before the next release.
=> Prevent arbitrary code eval

.gitignore, quantities/dimensionality.py, quantities/quantity.py, quantities/tests/test_umath.py
The parsing added in the latest release does not work with development version and breaks MNE workflow here: https://github.com/mne-tools/mne-python/pull/12815
https://github.com/mne-tools/mne-python/actions/runs/10577439355/job/29305416424#step:17:67
=> Fix numpy version string parsing

quantities/registry.py, quantities/tests/test_arithmetic.py, quantities/tests/test_conversion.py, quantities/units/time.py
@apdavison while working on updating the min the Neo ci discovered that `min` is used for minute. So I need to remove that from the builtins. There was no test for this in quantities ci.
=> Fix registry for `min` in buitlins

quantities/quantity.py, quantities/tests/test_methods.py
The new "plain" property returns a copy of the quantity as a plain number provided that the quantity is dimensionless. For example:
import quantities as pq
t = 2 * pq.ms
f = 3 * pq.MHz
n = (t*f).plain # n will be 6000
If the quantity is not dimensionless, a conversion error is raised.
Closes #247.
=> Added "plain" property to quantity
